### ISSUE TITLE
Example issue

### ISSUE THREAD

**Issue by boomboompower** [boomboompower/SimpleChatAlert#2]
If you are going to report an issue with the plugin, please follow this format! Check out https://github.com/boomboompower/SimpleChatAlert/wiki/Commands for help!

**Server Version:** 1.9.4

**Running:** Spigot

**NMS Version:** v1_9_R2

**Plugin Version:** 9.0

**Error in console:**

> [18:30:54][Server thread/ERROR]: Could not load 'plugins\SimpleChatAlert-9.0-SNAPSHOT.jar' in folder 'plugins'
> org.bukkit.plugin.InvalidPluginException: Cannot find main class `me.boomboompower.sca.SimpleChatAlert'
> 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:66) ~[Server.jar:git-Spigot-4af49dc-23da8b0]
> 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[Server.jar:git-Spigot-4af49dc-23da8b0]
> 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[Server.jar:git-Spigot-4af49dc-23da8b0]
> 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [Server.jar:git-Spigot-4af49dc-23da8b0]
> 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:296) [Server.jar:git-Spigot-4af49dc-23da8b0]
> 	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [Server.jar:git-Spigot-4af49dc-23da8b0]
> 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [Server.jar:git-Spigot-4af49dc-23da8b0]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
> Caused by: java.lang.ClassNotFoundException: me.boomboompower.sca.SimpleChatAlert
> 	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_73]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Server.jar:git-Spigot-4af49dc-23da8b0]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Server.jar:git-Spigot-4af49dc-23da8b0]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_73]
> 	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_73]
> 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[Server.jar:git-Spigot-4af49dc-23da8b0]
> 	... 7 more

**Comment by boomboompower** [comment]
# _**Please note:**_
This is just an example issue. It **IS NOT** a real issue.
